### PR TITLE
fix: setLanguage() should not set 'detail--visible' class

### PR DESCRIPTION
**Pull request by bobd9978**

### CODE REVIEW

**Comment by StommePoes** [comment]
Code changes look ok to me for now. We'll wait for Travis.

**Comment by umahaea** [comment]
This change does not break regression which is good. However, we would need selenium tests for this change.

**Comment by wyseguyonline** [comment]
LGTM

**Comment by songwei1990** [comment]
SQE from PI side have tested the code, and added new selenium and appium tests suites for this change.

**Comment by umahaea** [comment]
Thanks @songwei1990 for testing it. Merging this change.

**Pull request merged**
