### PR TITLE
gh-20: Added the main entry to `package.json`

### LINKED ISSUE #20: Main entry has not been specified in the package.json
`contextual-help` module cannot be used as follows since the main entry of package.json has not been specified.

```
var ContextualHelp = require('@pearson-components/contextual-help');
ContextualHelp.init();
```

Regards,
@dinukadesilva

### PR DESCRIPTION
**Pull request by dinukadesilva**
this fixes #20

### CODE REVIEW

**Comment by StommePoes** [comment]
If my PR for the style updates is ready today, I can just merge this change with mine so there'll be a single release fixing 2 things. If I'm delayed, I'll just merge this PR into master today and it can have its own release.

**Comment by JasonLantz** [comment]
can we add an author field as well:
"author": "Pearson Design Accelerator <pearson-design-accelerator@pearson.com>",

**Comment by StommePoes** [comment]
Sure

**Comment by umahaea** [comment]
CI's green. Selenium Tests pass, so good with QA.

**Pull request merged**
